<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Achievement' => 'Logro',
    'Achievement has been succesfully created.' => 'Logro ha sido creado con éxito',
    'Achievement has been succesfully deleted.' => 'Logro ha sido eliminado con éxito',
    'Achievement has been succesfully edited.' => 'Logro ha sido editado con éxito',
    'Achievement not deleted: ' => 'Logro no eliminada: ',
    'Editing achievement' => 'Editando logro',
    'Name' => 'Nombre',
    'New achievement' => 'Nuevo logro',
    'Please fill out the following fields with achievement data:' => 'Por favor rellene los campos con los datos del logro:',
    'Repeatable' => 'Repetible',
    'Reward' => 'Recompensa',
];
