<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Editing person' => 'Editando persona',
    'Email' => 'Correo electrónico',
    'Name' => 'Nombre',
    'New group achievement' => 'Nuevo logro grupal',
    'New person' => 'Nueva persona',
    'New person achievement' => '@@Nuevo logro de persona@@',
    'Person' => 'Persona',
    'Person achievement has been succesfully created.' => '@@Logro de persona exitosamente creado.@@',
    'Person achievement has been succesfully deleted.' => 'Logro de persona exitosamente eliminado.',
    'Person achievement not delete:' => 'Logro de persona no eliminado: ',
    'Person achievement not saved: ' => '@@Logro de persona no guardado: @@',
    'Person has been succesfully created.' => 'Persona ha sido creada con éxito.',
    'Person has been succesfully deleted.' => 'Persona ha sido eliminada con éxito.',
    'Person has been succesfully edited.' => 'Persona ha sido editada con éxito.',
    'Person not deleted: ' => 'Persona no eliminada: ',
    'Please fill out the following fields to register the group achievement:' => 'Por favor rellene los campos para registrar el logro del grupo:',
    'Please fill out the following fields to register the person achievement:' => '@@Por favor rellene los campos con los datos del logro de la persona:@@',
    'Please fill out the following fields with person data:' => 'Por favor rellene los campos con los datos de la persona:',
    'Select a person ...' => 'Elija una persona...',
    'Select an achievement ...' => 'Elija un logro...',
    'Surname' => 'Apellido',
];
