<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account data not saved: ' => 'Datos de cuenta no salvados: ',
    'Editing user' => 'Editando usuario',
    'If you forgot your password you can ' => 'Si olvidó su contraseña puede ',
    'Is administrator' => 'Es administrador',
    'My Account' => 'Mi cuenta',
    'New user' => 'Nuevo usuario',
    'Password' => 'Contraseña',
    'Password confirmation' => 'Confirmar contraseña',
    'Please fill out the following fields with user personal data:' => 'Por favor rellene el siguiente formulario con los datos personales del usuario:',
    'Please fill out the following fields with your personal data:' => 'Por favor rellene el siguiente formulario con sus datos personales:',
    'Remember me' => 'Recuerdame',
    'Sign in' => 'Ingresar',
    'User has been succesfully created.' => 'Usuario creado existosamente.',
    'User has been succesfully deleted.' => 'Usuario eliminado exitosamente.',
    'User has been succesfully edited.' => 'Usuario editado exitosamente.',
    'Username' => 'Nombre de usuario',
    'Your personal data has been succesfully saved.' => 'Sus datos persona han sido salvados con éxito.',
    'reset it' => 'reiniciarla',
];
